-- Use Dictinct with Orderby to remove duplicate rows
SELECT DISTINCT(E.EMP_NO),
E.FIRST_NAME, 
E.LAST_NAME,
T.TITLE,
T.FROM_DATE,
T.TO_DATE
INTO retirement_titles
FROM EMPLOYEES AS E
INNER JOIN TITLES AS T ON T.EMP_NO = E.EMP_NO
WHERE (e.birth_date BETWEEN '1952-01-01' AND '1955-12-31')
ORDER BY E.EMP_NO;

/*unique_titles*/
SELECT DISTINCT ON (EMP_NO) EMP_NO,
FIRST_NAME,
LAST_NAME,
RT.TITLE
INTO unique_titles
FROM RETIREMENT_TITLES AS RT
WHERE RT.TO_DATE = '9999-01-01'
ORDER BY EMP_NO DESC;

/*retiring_titles*/
SELECT COUNT(TITLE), TITLE
INTO retiring_titles
FROM UNIQUE_TITLES
GROUP BY TITLE
ORDER BY COUNT(TITLE) DESC;

/*mentorship_eligibilty*/
SELECT DISTINCT ON(E.EMP_NO) E.EMP_NO,
E.FIRST_NAME, 
E.LAST_NAME,
E.BIRTH_DATE,
T.FROM_DATE,
T.TO_DATE,
T.TITLE
INTO mentorship_eligibilty
FROM EMPLOYEES AS E
INNER JOIN DEPT_EMP AS DE ON DE.EMP_NO = E.EMP_NO
INNER JOIN TITLES AS T ON T.EMP_NO = E.EMP_NO
WHERE T.TO_DATE ='9999-01-01'
AND (E.BIRTH_DATE BETWEEN '1965-01-01' AND '1965-12-31')
ORDER BY E.EMP_NO ;
